/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phoopyaepyaesoe1;

import MainPage.MainPage;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author lenovo
 */
public class MarkSystem3 extends javax.swing.JFrame {
GridBagLayout grid=new GridBagLayout();
FirstYr p1;
SecondYr p2;
ThirdYrCT p3;
ThirdYrCS p4;
FourthYrSE p5;
FourthYrKE p6;
FourthYrHPC p7;
FourthYrBIS p8;
FourthYrCN p9;
FourthYrCS p10;
FourthYrES p11;
FinalYrSE p12;
FinalYrKE p13;
FinalYrHPC p14;
FinalYrBIS p15;
FinalYrCN p16;
FinalYrCS p17;
FinalYrES p18;
int i=0,j=0,k=0;
    /**
     * Creates new form MarkSystem3
     */
    public MarkSystem3() {
        initComponents();
       setExtendedState(JFrame.MAXIMIZED_BOTH);
        p1=new FirstYr();
        p2=new SecondYr();
        p3=new ThirdYrCT();
        p4=new ThirdYrCS();
        p5=new FourthYrSE();
        p6=new FourthYrKE();
        p7=new FourthYrHPC();
        p8=new FourthYrBIS();
        p9=new FourthYrCN();
        p10=new FourthYrCS();
        p11=new FourthYrES();
        p12=new FinalYrSE();
        p13=new FinalYrKE();
        p14=new FinalYrHPC();
        p15=new FinalYrBIS();
        p16=new FinalYrCN();
        p17=new FinalYrCS();
        p18=new FinalYrES();
        ShowPanel.setLayout(grid);
        GridBagConstraints gc=new GridBagConstraints();
        gc.gridx=0;
        gc.gridy=0;
        ShowPanel.add(p1,gc);
        ShowPanel.add(p2,gc);
        ShowPanel.add(p3,gc);
        ShowPanel.add(p4,gc);
        ShowPanel.add(p5,gc);
        ShowPanel.add(p6,gc);
        ShowPanel.add(p7,gc);
        ShowPanel.add(p8,gc);
        ShowPanel.add(p9,gc);
        ShowPanel.add(p10,gc);
        ShowPanel.add(p11,gc);
        ShowPanel.add(p12,gc);
        ShowPanel.add(p13,gc);
        ShowPanel.add(p14,gc);
        ShowPanel.add(p15,gc);
        ShowPanel.add(p16,gc); 
        ShowPanel.add(p17,gc);
        ShowPanel.add(p18,gc);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        CT.setVisible(false);
        CS.setVisible(false);
        SE.setVisible(false);
        KE.setVisible(false);
        HPC.setVisible(false);
        ComS.setVisible(false);
        CN.setVisible(false);
        ES.setVisible(false);
        BIS.setVisible(false); 
        SE1.setVisible(false);
        KE1.setVisible(false);
        HPC1.setVisible(false);
        ComS1.setVisible(false);
        CN1.setVisible(false);
        ES1.setVisible(false);
        BIS1.setVisible(false); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        first_year = new javax.swing.JLabel();
        second_year = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TR3 = new javax.swing.JLabel();
        CS = new javax.swing.JLabel();
        KE = new javax.swing.JLabel();
        CT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TR6 = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        HPC = new javax.swing.JLabel();
        CN = new javax.swing.JLabel();
        ComS = new javax.swing.JLabel();
        ES = new javax.swing.JLabel();
        BIS = new javax.swing.JLabel();
        SE1 = new javax.swing.JLabel();
        TR8 = new javax.swing.JLabel();
        KE1 = new javax.swing.JLabel();
        HPC1 = new javax.swing.JLabel();
        BIS1 = new javax.swing.JLabel();
        CN1 = new javax.swing.JLabel();
        ComS1 = new javax.swing.JLabel();
        ES1 = new javax.swing.JLabel();
        ShowPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new java.awt.GridBagLayout());

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Panel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phoopyaepyaesoe1/admin.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Admin");

        first_year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first_year.setForeground(new java.awt.Color(255, 255, 255));
        first_year.setText("First Year");
        first_year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                first_yearMouseClicked(evt);
            }
        });

        second_year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        second_year.setForeground(new java.awt.Color(255, 255, 255));
        second_year.setText("Second Year");
        second_year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                second_yearMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        TR3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TR3.setForeground(new java.awt.Color(255, 255, 255));
        TR3.setText("Third Year");
        TR3.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                TR3AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        TR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TR3MouseClicked(evt);
            }
        });

        CS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CS.setForeground(new java.awt.Color(255, 255, 255));
        CS.setText("CS");
        CS.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                CSAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        CS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSMouseClicked(evt);
            }
        });

        KE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KE.setForeground(new java.awt.Color(255, 255, 255));
        KE.setText("KE");
        KE.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                KEAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        KE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KEMouseClicked(evt);
            }
        });

        CT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CT.setForeground(new java.awt.Color(255, 255, 255));
        CT.setText("CT");
        CT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                CTAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTMouseClicked(evt);
            }
        });

        jButton1.setText("View Results>>>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TR6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TR6.setForeground(new java.awt.Color(255, 255, 255));
        TR6.setText("Fourth Year");
        TR6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TR6AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TR6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TR6MouseClicked(evt);
            }
        });

        SE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SE.setForeground(new java.awt.Color(255, 255, 255));
        SE.setText("SE");
        SE.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                SEAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        SE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEMouseClicked(evt);
            }
        });

        HPC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HPC.setForeground(new java.awt.Color(255, 255, 255));
        HPC.setText("HPC");
        HPC.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                HPCAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        HPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HPCMouseClicked(evt);
            }
        });

        CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CN.setForeground(new java.awt.Color(255, 255, 255));
        CN.setText("CN");
        CN.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                CNAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        CN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CNMouseClicked(evt);
            }
        });

        ComS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComS.setForeground(new java.awt.Color(255, 255, 255));
        ComS.setText("CS");
        ComS.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                ComSAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        ComS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComSMouseClicked(evt);
            }
        });

        ES.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ES.setForeground(new java.awt.Color(255, 255, 255));
        ES.setText("ES");
        ES.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                ESAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        ES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ESMouseClicked(evt);
            }
        });

        BIS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BIS.setForeground(new java.awt.Color(255, 255, 255));
        BIS.setText("BIS");
        BIS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                BISAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        BIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BISMouseClicked(evt);
            }
        });

        SE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SE1.setForeground(new java.awt.Color(255, 255, 255));
        SE1.setText("SE");
        SE1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                SE1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SE1MouseClicked(evt);
            }
        });

        TR8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TR8.setForeground(new java.awt.Color(255, 255, 255));
        TR8.setText("Final Year");
        TR8.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TR8AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TR8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TR8MouseClicked(evt);
            }
        });

        KE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KE1.setForeground(new java.awt.Color(255, 255, 255));
        KE1.setText("KE");
        KE1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                KE1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        KE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KE1MouseClicked(evt);
            }
        });

        HPC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HPC1.setForeground(new java.awt.Color(255, 255, 255));
        HPC1.setText("HPC");
        HPC1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                HPC1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        HPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HPC1MouseClicked(evt);
            }
        });

        BIS1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BIS1.setForeground(new java.awt.Color(255, 255, 255));
        BIS1.setText("BIS");
        BIS1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                BIS1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        BIS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BIS1MouseClicked(evt);
            }
        });

        CN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CN1.setForeground(new java.awt.Color(255, 255, 255));
        CN1.setText("CN");
        CN1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                CN1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CN1MouseClicked(evt);
            }
        });

        ComS1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComS1.setForeground(new java.awt.Color(255, 255, 255));
        ComS1.setText("CS");
        ComS1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                ComS1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComS1MouseClicked(evt);
            }
        });

        ES1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ES1.setForeground(new java.awt.Color(255, 255, 255));
        ES1.setText("ES");
        ES1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                ES1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ES1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ES1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(CS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CT)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_year, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(second_year)
                            .addComponent(TR3)
                            .addComponent(TR6)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                        .addComponent(SE1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KE1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HPC1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BIS1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CN1))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(SE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HPC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BIS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(ES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComS))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(ES1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComS1))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(TR8)))))
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(first_year)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(second_year)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TR3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TR6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HPC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ES, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TR8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SE1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KE1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIS1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CN1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ES1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComS1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1575, Short.MAX_VALUE)
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phoopyaepyaesoe1/games1.png"))); // NOI18N
        jMenuItem5.setText("Game");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Log out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChooseYR choose=new ChooseYR();
        choose.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void CTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTMouseClicked
        // TODO add your handling code here:
        p3.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_CTMouseClicked

    private void CTAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CTAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CTAncestorMoved

    private void KEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KEMouseClicked
        // TODO add your handling code here:
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_KEMouseClicked

    private void KEAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_KEAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_KEAncestorMoved

    private void CSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSMouseClicked
        // TODO add your handling code here:
        p4.setVisible(true);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        
    }//GEN-LAST:event_CSMouseClicked

    private void CSAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_CSAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CSAncestorMoved

    private void TR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TR3MouseClicked

        if(i==0)
        {
            i=1;
            CT.setVisible(true);
            CS.setVisible(true);
            
        }
        else
        {
            i=0;
            CT.setVisible(false);
            CS.setVisible(false);
           // p1.setVisible(true);
        }
    }//GEN-LAST:event_TR3MouseClicked
   public void bg_button(JLabel lbl)
   {
       lbl.setBackground(new Color(33,63,86));
   }
    private void TR3AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_TR3AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TR3AncestorMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void second_yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_second_yearMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_second_yearMouseClicked

    private void first_yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_first_yearMouseClicked
        p1.setVisible(true);
        p2.setVisible(false);
        // TODO add your handling code here:
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        
    }//GEN-LAST:event_first_yearMouseClicked

    private void TR6AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TR6AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TR6AncestorMoved

    private void TR6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TR6MouseClicked
        // TODO add your handling code here:
         if(j==0)
        {
            j=1;
            SE.setVisible(true);
        KE.setVisible(true);
        HPC.setVisible(true);
        ComS.setVisible(true);
        CN.setVisible(true);
        ES.setVisible(true);
        BIS.setVisible(true);
            
        }
        else
        {
            j=0;
        SE.setVisible(false);
        KE.setVisible(false);
        HPC.setVisible(false);
        ComS.setVisible(false);
        CN.setVisible(false);
        ES.setVisible(false);
        BIS.setVisible(false);
        }
      
    }//GEN-LAST:event_TR6MouseClicked

    private void SEAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_SEAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SEAncestorMoved

    private void SEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        
       
    }//GEN-LAST:event_SEMouseClicked

    private void HPCAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_HPCAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_HPCAncestorMoved

    private void HPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HPCMouseClicked
        // TODO add your handling code here:
           p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(true);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        
    }//GEN-LAST:event_HPCMouseClicked

    private void CNAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_CNAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CNAncestorMoved

    private void CNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CNMouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(true);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_CNMouseClicked

    private void ComSAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ComSAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ComSAncestorMoved

    private void ComSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComSMouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(true);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
        
    }//GEN-LAST:event_ComSMouseClicked

    private void ESAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ESAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ESAncestorMoved

    private void ESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESMouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(true);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_ESMouseClicked

    private void BISAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BISAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BISAncestorMoved

    private void BISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BISMouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(true);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_BISMouseClicked

    private void SE1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SE1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SE1AncestorMoved

    private void SE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SE1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(true);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_SE1MouseClicked

    private void TR8AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TR8AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TR8AncestorMoved

    private void TR8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TR8MouseClicked
        // TODO add your handling code here:
           if(k==0)
        {
            k=1;
        SE1.setVisible(true);
        KE1.setVisible(true);
        HPC1.setVisible(true);
        ComS1.setVisible(true);
        CN1.setVisible(true);
        ES1.setVisible(true);
        BIS1.setVisible(true);
            
        }
        else
        {
            k=0;
        SE1.setVisible(false);
        KE1.setVisible(false);
        HPC1.setVisible(false);
        ComS1.setVisible(false);
        CN1.setVisible(false);
        ES1.setVisible(false);
        BIS1.setVisible(false);
        }
    }//GEN-LAST:event_TR8MouseClicked

    private void KE1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_KE1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_KE1AncestorMoved

    private void KE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KE1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(true);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_KE1MouseClicked

    private void HPC1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HPC1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_HPC1AncestorMoved

    private void HPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HPC1MouseClicked
        // TODO add your handling code here:
          p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(true);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_HPC1MouseClicked

    private void BIS1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BIS1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BIS1AncestorMoved

    private void BIS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIS1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(true);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_BIS1MouseClicked

    private void CN1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CN1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CN1AncestorMoved

    private void CN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CN1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(true);
        p17.setVisible(false);
        p18.setVisible(false);
    }//GEN-LAST:event_CN1MouseClicked

    private void ComS1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComS1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ComS1AncestorMoved

    private void ComS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComS1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(true);
        p18.setVisible(false);                              
    }//GEN-LAST:event_ComS1MouseClicked

    private void ES1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ES1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ES1AncestorMoved

    private void ES1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ES1MouseClicked
        // TODO add your handling code here:
        p4.setVisible(false);
        p3.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p14.setVisible(false);
        p15.setVisible(false);
        p16.setVisible(false);
        p17.setVisible(false);
        p18.setVisible(true);
                                 
    }//GEN-LAST:event_ES1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MainPage nn=new MainPage();
        nn.setVisible(true);
        this.setVisible(false);
              
    }//GEN-LAST:event_jMenuItem4ActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkSystem3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkSystem3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkSystem3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkSystem3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

       
 
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkSystem3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIS;
    private javax.swing.JLabel BIS1;
    private javax.swing.JLabel CN;
    private javax.swing.JLabel CN1;
    private javax.swing.JLabel CS;
    private javax.swing.JLabel CT;
    private javax.swing.JLabel ComS;
    private javax.swing.JLabel ComS1;
    private javax.swing.JLabel ES;
    private javax.swing.JLabel ES1;
    private javax.swing.JLabel HPC;
    private javax.swing.JLabel HPC1;
    private javax.swing.JLabel KE;
    private javax.swing.JLabel KE1;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel SE;
    private javax.swing.JLabel SE1;
    private javax.swing.JPanel ShowPanel;
    private javax.swing.JLabel TR3;
    private javax.swing.JLabel TR6;
    private javax.swing.JLabel TR8;
    private javax.swing.JLabel first_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel second_year;
    // End of variables declaration//GEN-END:variables

   
}
