/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phoopyaepyaesoe1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class SecondYr extends javax.swing.JPanel {

    /**
     * Creates new form SecondYr
     */
    public SecondYr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        S201 = new javax.swing.JTextField();
        SEng = new javax.swing.JTextField();
        S202 = new javax.swing.JTextField();
        S203 = new javax.swing.JTextField();
        S204 = new javax.swing.JTextField();
        S205 = new javax.swing.JTextField();
        S206 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        SName = new javax.swing.JTextField();
        SRollno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        S203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S203ActionPerformed(evt);
            }
        });

        jLabel1.setText("201");

        jLabel2.setText("Eng");

        jLabel3.setText("202");

        jLabel4.setText("203");

        jLabel5.setText("204");

        jLabel6.setText("205");

        jLabel7.setText("206");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNameActionPerformed(evt);
            }
        });

        jLabel8.setText("Roll no");

        jLabel9.setText("Name");

        jLabel10.setText("Second Year");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phoopyaepyaesoe1/uitcopy.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(52, 52, 52))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(66, 66, 66)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(57, 57, 57)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(66, 66, 66)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(66, 66, 66)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(66, 66, 66)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(66, 66, 66)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(S206, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SRollno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S201, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SEng, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S202, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S204, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S203, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S205, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel11)
                                        .addGap(0, 198, Short.MAX_VALUE)))))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel10)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(S204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(SRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(SName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(S201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(S202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(S203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(S206, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNameActionPerformed

    private void S203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S203ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S203ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String t=S201.getText();
//        String t1=SEng.getText();
//        String t2=S202.getText();
//        String t3=S203.getText();
//        String t4=S204.getText();
//        String t5=S205.getText();
//        String t6=S206.getText();
//        InsertSecond insert1=new InsertSecond();
//        insert1.Rollno=SRollno.getText();
//        insert1.NAME=SName.getText();
//        insert1.A201=Integer.parseInt(t);
//        insert1.AEng=Integer.parseInt(t1);
//        insert1.A203=Integer.parseInt(t3);
//        insert1.A202=Integer.parseInt(t2);
//        insert1.A204=Integer.parseInt(t4);
//        insert1.A205=Integer.parseInt(t5);
//        insert1.A206=Integer.parseInt(t6);
//        int Ssub1=Integer.parseInt(t);
//        int Ssub2=Integer.parseInt(t1);
//        int Ssub3=Integer.parseInt(t2);
//        int Ssub4=Integer.parseInt(t3);
//        int Ssub5=Integer.parseInt(t4);
//        int Ssub6=Integer.parseInt(t5);
//        int Ssub7=Integer.parseInt(t6);
        InsertSecond nn=new InsertSecond();
        nn.Rollno=SRollno.getText();
        nn.NAME=SName.getText();
        nn.A201=Integer.parseInt(S201.getText());
        nn.A202=Integer.parseInt(S202.getText());
        nn.AEng=Integer.parseInt(SEng.getText());
        nn.A203=Integer.parseInt(S203.getText());
        nn.A204=Integer.parseInt(S204.getText());
        nn.A205=Integer.parseInt(S205.getText());
        nn.A206=Integer.parseInt(S206.getText());

        int Ssub1=Integer.parseInt(S201.getText());
        int Ssub2=Integer.parseInt(SEng.getText());
        int Ssub3=Integer.parseInt(S202.getText());
        int Ssub4=Integer.parseInt(S203.getText());
        int Ssub5=Integer.parseInt(S205.getText());
        int Ssub6=Integer.parseInt(S205.getText());
        int Ssub7=Integer.parseInt(S206.getText());
        if(Ssub1>100 || Ssub2>100 || Ssub3>100 || Ssub4>100 || Ssub5>100 || Ssub7>100 || Ssub6>100)
         {
             JOptionPane.showMessageDialog(this,"Invalid number","Error",JOptionPane.ERROR_MESSAGE);
                SRollno.setText(null);
            SName.setText(null);
           S201.setText(null);
            SEng.setText(null);
            S202.setText(null);
            S203.setText(null);
            S204.setText(null);
            S205.setText(null);
            S206.setText(null);
         }
        else{
        int total=Ssub1+Ssub2+Ssub3+Ssub4+Ssub5+Ssub5+Ssub6+Ssub7;
        nn.Total=total;
        try {
            nn.insert2();
        } catch (SQLException ex) {
            Logger.getLogger(SecondYr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondYr.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scaculategrade secondyr=new Scaculategrade();
        secondyr.SRollno=SRollno.getText();;
         secondyr.SNAME=SName.getText();
            
        
         if(Ssub1<=100 && Ssub1>=80)
         {
             secondyr.S201="A";
         }
         else if(Ssub1<=80 && Ssub1>=60)
         {
            secondyr.S201="B";
         }
         else if(Ssub1<=60 && Ssub1>=40)
         {
             secondyr.S201="C";
         }
         else if(Ssub1<=40 && Ssub1>=20)
         {
             secondyr.S201="D";
         }
         else
         {
             secondyr.S201="E";
         }
       
           if(Ssub2<=100 && Ssub2>=80)
         {
            secondyr.SEng="A";
         }
         else if(Ssub2<=80 && Ssub2>=60)
         {
            secondyr.SEng="B";
         }
         else if(Ssub2<=60 && Ssub2>=40)
         {
            secondyr.SEng="C";
         }
         else if(Ssub2<=40 && Ssub2>=20)
         {
            secondyr.SEng="D";
         }
         else
         {
            secondyr.SEng="E";
         }
        
          if(Ssub3<=100 && Ssub3>=80)
         {
            secondyr.S202="A";
         }
         else if(Ssub3<=80 && Ssub3>=60)
         {
             secondyr.S202="B";
         }
         else if(Ssub3<=60 && Ssub3>=40)
         {
             secondyr.S202="C";
         }
         else if(Ssub3<=40 && Ssub3>=20)
         {
             secondyr.S202="D";
         }
         else
         {
             secondyr.S202="E";
         }
       
        
              if(Ssub4<=100 && Ssub4>=80)
         {
             secondyr.S203="A";
         }
         else if(Ssub4<=80 && Ssub4>=60)
         {
             secondyr.S203="B";
         }
         else if(Ssub4<=60 && Ssub4>=40)
         {
             secondyr.S203="C";
         }
         else if(Ssub4<=40 && Ssub4>=20)
         {
             secondyr.S203="D";
         }
         else
         {
             secondyr.S203="E";
         }
           
               if(Ssub5<=100 && Ssub5>=80)
         {
          secondyr.S204="A";
         }
         else if(Ssub5<=80 && Ssub5>=60)
         {
             secondyr.S204="B";
         }
         else if(Ssub5<=60 && Ssub5>=40)
         {
             secondyr.S204="C";
         }
         else if(Ssub5<=40 && Ssub5>=20)
         {
             secondyr.S204="D";
         }
         else
         {
             secondyr.S204="E";
         }
             
          
        
           if(Ssub6<=100 && Ssub6>=80)
         {
             secondyr.S205="A";
         }
         else if(Ssub6<=80 && Ssub6>=60)
         {
             secondyr.S205="B";
         }
         else if(Ssub6<=60 && Ssub6>=40)
         {
             secondyr.S205="C";
         }
         else if(Ssub6<=40 && Ssub6>=20)
         {
             secondyr.S205="D";
         }
         else
         {
            secondyr.S205="E";
         }
             
          if(Ssub7<=100 && Ssub7>=80)
         {
             secondyr.S206="A";
         }
         else if(Ssub7<=80 && Ssub7>=60)
         {
             secondyr.S206="B";
         }
         else if(Ssub7>=60 && Ssub7<=40)
         {
             secondyr.S206="C";
         }
         else if(Ssub7<=40 && Ssub7>=20)
         {
             secondyr.S206="D";
         }
         else
         {
             secondyr.S206="E";
         } 
          secondyr.Total=total;
        try {
            secondyr.Secondcaculate();
              SRollno.setText(null);
            SName.setText(null);
            S201.setText(null);
            SEng.setText(null);
            S202.setText(null);
            S203.setText(null);
            S204.setText(null);
            S205.setText(null);
            S206.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(SecondYr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondYr.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed
          
       
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField S201;
    private javax.swing.JTextField S202;
    private javax.swing.JTextField S203;
    private javax.swing.JTextField S204;
    private javax.swing.JTextField S205;
    private javax.swing.JTextField S206;
    private javax.swing.JTextField SEng;
    private javax.swing.JTextField SName;
    private javax.swing.JTextField SRollno;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
