/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phoopyaepyaesoe1;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;
import java.sql.SQLDataException;


/**
 *
 * @author lenovo
 */
public class ThirdYrCS extends javax.swing.JPanel {
//InsertDBMark i=new InsertDBMark();
/**
     * Creates new form FirstYr
     */ 
    public ThirdYrCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CS304 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CS302 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CS305 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CS306 = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        CS301 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CSName = new javax.swing.JTextField();
        Eng = new javax.swing.JLabel();
        CSEng = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        CSRollno = new javax.swing.JTextField();
        CS303 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("301");

        jLabel3.setText("ThirdYear CS");

        jLabel4.setText("304");

        CS304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS304ActionPerformed(evt);
            }
        });

        jLabel5.setText("302");

        CS302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS302ActionPerformed(evt);
            }
        });

        jLabel6.setText("305");

        CS305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS305ActionPerformed(evt);
            }
        });

        jLabel7.setText("306");

        CS306.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS306ActionPerformed(evt);
            }
        });

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        CS301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS301ActionPerformed(evt);
            }
        });

        jLabel8.setText("Name");

        CSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSNameActionPerformed(evt);
            }
        });

        Eng.setText("English");

        CSEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSEngActionPerformed(evt);
            }
        });

        ID.setText("Roll no");

        CSRollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSRollnoActionPerformed(evt);
            }
        });

        CS303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS303ActionPerformed(evt);
            }
        });

        jLabel9.setText("303");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phoopyaepyaesoe1/uitcopy.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(Eng, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insert)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CSRollno, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CSName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS301, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CSEng, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS302, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS303, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS304, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS305, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CS306, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel3)
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ID)
                                            .addComponent(CSRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(CSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(CS301, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(CSEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Eng))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CS302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CS303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(CS304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CS305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CS306, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addComponent(Insert)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CS304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS304ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS304ActionPerformed

    private void CS302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS302ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS302ActionPerformed

    private void CS305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS305ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS305ActionPerformed

    private void CS306ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS306ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS306ActionPerformed

    private void CS301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS301ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS301ActionPerformed

    private void CSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSNameActionPerformed

    private void CSEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSEngActionPerformed

    private void CSRollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSRollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSRollnoActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed

        // TODO add your handling code here:
     
        /*InsertDBMark i=new InsertDBMark();
        i.NAME=FName.getText();
        try {
        i.insert();
        } catch (SQLException ex) {
        Logger.getLogger(FirstYr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(FirstYr.class.getName()).log(Level.SEVERE, null, ex);
        }*/
            int sub1=Integer.parseInt(CS301.getText());
        int sub2=Integer.parseInt(CSEng.getText());
        int sub3=Integer.parseInt(CS302.getText());
        int sub4=Integer.parseInt(CS303.getText());
        int sub5=Integer.parseInt(CS304.getText());
        int sub6=Integer.parseInt(CS305.getText());
         int sub7=Integer.parseInt(CS306.getText());
     InsertDBCS insert=new InsertDBCS();
     insert.CSRollno=CSRollno.getText();
     insert.CSNAME=CSName.getText();
     insert.CS301=Integer.parseInt(CS301.getText());
     insert.CSEng=Integer.parseInt(CSEng.getText());
     insert.CS302=Integer.parseInt(CS302.getText());
     insert.CS303=Integer.parseInt(CS303.getText());
     insert.CS304=Integer.parseInt(CS304.getText());
     insert.CS305=Integer.parseInt(CS305.getText());
     insert.CS306=Integer.parseInt(CS306.getText());
        int total=sub1+sub2+sub3+sub4+sub5+sub6+sub7;
      insert.CSTotal=total;
        try {
            insert.csinsert();
        } catch (SQLException ex) {
            Logger.getLogger(ThirdYrCS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThirdYrCS.class.getName()).log(Level.SEVERE, null, ex);
        }
        CScaculategrade caculate=new CScaculategrade();
         
            
         caculate.CSRollno=CSRollno.getText();;
         caculate.CSName=CSName.getText();
            
          //101
         if(sub1<=100 && sub1>=80)
         {
             caculate.CS301="A";
         }
         else if(sub1<=80 && sub1>=60)
         {
             caculate.CS301="B";
         }
         else if(sub1<=60 && sub1>=40)
         {
             caculate.CS301="C";
         }
         else if(sub1<=40 && sub1>=20)
         {
             caculate.CS301="D";
         }
         else
         {
             caculate.CS301="E";
         }
         //101
         
         //Eng
           if(sub2<=100 && sub2>=80)
         {
             caculate.CSEng="A";
         }
         else if(sub2<=80 && sub2>=60)
         {
             caculate.CSEng="B";
         }
         else if(sub2<=60 && sub2>=40)
         {
             caculate.CSEng="C";
         }
         else if(sub2<=40 && sub2>=20)
         {
             caculate.CSEng="D";
         }
         else
         {
             caculate.CSEng="E";
         }
        //English
        
        //Myanmar
          if(sub3<=100 && sub3>=80)
         {
             caculate.CS302="A";
         }
         else if(sub3<=80 && sub3>=60)
         {
             caculate.CS302="B";
         }
         else if(sub3<=60 && sub3>=40)
         {
             caculate.CS302="C";
         }
         else if(sub3<=40 && sub3>=20)
         {
             caculate.CS302="D";
         }
         else
         {
             caculate.CS302="E";
         }
        //Myanmar
   
           //102
              if(sub4<=100 && sub4>=80)
         {
             caculate.CS303="A";
         }
         else if(sub4<=80 && sub4>=60)
         {
             caculate.CS303="B";
         }
         else if(sub4<=60 && sub4>=40)
         {
             caculate.CS303="C";
         }
         else if(sub4<=40 && sub4>=20)
         {
             caculate.CS303="D";
         }
         else
         {
             caculate.CS303="E";
         }
              //102
              
              //103
               if(sub5<=100 && sub5>=80)
         {
             caculate.CS304="A";
         }
         else if(sub5<=80 && sub5>=60)
         {
             caculate.CS304="B";
         }
         else if(sub5<=60 && sub5>=40)
         {
             caculate.CS304="C";
         }
         else if(sub5<=40 && sub5>=20)
         {
             caculate.CS304="D";
         }
         else
         {
             caculate.CS304="E";
         }
              //103
              
              //104
          if(sub6<=100 && sub6>=80)
         {
             caculate.CS305="A";
         }
         else if(sub6<=80 && sub6>=60)
         {
             caculate.CS305="B";
         }
         else if(sub6>=60 && sub6<=40)
         {
             caculate.CS305="C";
         }
         else if(sub6<=40 && sub6>=20)
         {
             caculate.CS305="D";
         }
         else
         {
             caculate.CS305="E";
         }   
          //104
          
          
        //Physics
           if(sub7<=100 && sub7>=80)
         {
             caculate.CS306="A";
         }
         else if(sub7<=80 && sub7>=60)
         {
             caculate.CS306="B";
         }
         else if(sub7<=60 && sub7>=40)
         {
             caculate.CS306="C";
         }
         else if(sub7<=40 && sub7>=20)
         {
             caculate.CS306="D";
         }
         else
         {
             caculate.CS306="E";
         }
           //Physics
           caculate.CSTotal=total;
        try {           
            caculate.third1caculate();
        } catch (SQLException ex) {
            Logger.getLogger(ThirdYrCS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThirdYrCS.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_InsertActionPerformed

    private void CS303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS303ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CS303ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CS301;
    public javax.swing.JTextField CS302;
    public javax.swing.JTextField CS303;
    public javax.swing.JTextField CS304;
    public javax.swing.JTextField CS305;
    public javax.swing.JTextField CS306;
    public javax.swing.JTextField CSEng;
    public javax.swing.JTextField CSName;
    public javax.swing.JTextField CSRollno;
    private javax.swing.JLabel Eng;
    private javax.swing.JLabel ID;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
